name: Deploy Gipsy Prod

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all history
          submodules: recursive
      - name: Deploy to server
        uses:  swznd/sftp-deploy@master
        with:
          host: ${{ secrets.PROD_SFTP_IP }}
          port: ${{ secrets.PROD_SFTP_PORT }}
          user: ${{ secrets.PROD_SFTP_USER }}
          password: ${{ secrets.PROD_SFTP_PASSWORD }}
          ignore: .github/**,.gitignore,**/.gitignore,**/.git/**
      - name: Restart running bot
        env:
          GIPSY_RESTART_PROD_ENDPOINT: ${{ secrets.GIPSY_RESTART_PROD_ENDPOINT }}
          GIPSY_RESTART_PROD_BEARER: ${{ secrets.GIPSY_RESTART_PROD_BEARER }}
        run: |
          curl $GIPSY_RESTART_PROD_ENDPOINT \
            -H 'Accept: application/json' \
            -H 'Content-Type: application/json' \
            -H 'Authorization: Bearer $GIPSY_RESTART_PROD_BEARER' \
            -X POST \
            -d '{
            "signal": "restart"
            }'